### ISSUE TITLE
Counter example ignoring input bounds

### ISSUE THREAD

**Issue by MarcelBulpr** [vas-group-imperial/VeriNet#6]
I am currently trying to make dnnv use this version of Verinet.
In dnnv, the constraints are set up in a way that the resulting output that Verinet sees is just a bool, so I am currently doing something like this:
```python
solver = VeriNet(use_gpu=True, max_procs=None)
objective = Objective(input_bounds, output_size=1, model=model)
objective.add_constraints(objective.output_vars[0] <= 1)
objective.add_constraints(objective.output_vars[0] >= 1)
```

However, Verinet always produces a counterexample in the first branch explored (Maximum depth reached: 0) which is outside the specified bounds.
I checked that the `input_bounds` has the correct shape and expected values (-e    +e) for every value.

I am sure that I am missing something here, any help would be greatly appreciated.

**Comment by pat676** [comment]
Hi, 

I would need more information to be sure, but I'll give it a go:

My immediate concern with the verification query is that VeriNet does not inherently support booleans. I assume the boolean condition of the network is encoded as floats? If so, any rounding error in the network would violate the output constraints, and the behaviour is as expected. 

Moreover, even if the network somehow avoids rounding errors, VeriNet could still experience them. It may thus be the case that VeriNet will never be able to prove that the networks' output is exactly 1, even after exhaustively exploring all branches. 

The situation could be resolved by adding some tolerance to the output constraints. However, the tolerance value would depend on the network architecture and size. If you expect outputs to be either 0 or 1, I would try a relatively large tolerance, for instance:

```
objective.add_constraints(objective.output_vars[0] <= 1.1)
objective.add_constraints(objective.output_vars[0] >= 0.9)
```

If this does not help, could you provide the following information: 

1) You say, "... Verinet always produces a counterexample in the first branch explored (Maximum depth reached: 0) which is outside the specified bounds". Do you mean input bounds, output bounds, or both? If it is input bounds, what is the magnitude of the elementwise violations? Could it be due to different floating point precisions? 
2) Could you provide a minimal reproducible example with code and ONNX model?

**Comment by MarcelBulpr** [comment]
Thank you for the quick reply!
After further investigation, I don't think it is a Verinet problem anymore.

I'm sorry for any inconvenience.
